# Generated by Django 2.2.24 on 2025-03-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230909_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='pure_phone',
        ),
    ]
