# Generated by Django 2.2.24 on 2025-03-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_flat_pure_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='host',
            new_name='owner',
        ),
    ]
